# Generated by Django 5.0.6 on 2024-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
