# Generated by Django 5.0.6 on 2024-06-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userinfo_options_alter_userinfo_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
